-- Explore All Objects in the database

SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore All columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'dim_customers';

 -- Dimensions Exploration

-- Explore All Countries our custoerms come from.
SELECT DISTINCT country FROM gold.dim_customers;

-- Explore All product Categories "The Major Divisions"
SELECT DISTINCT category FROM gold.dim_products;

-- Explore All product Categories "The major Divisions" (Further Drilling Down)
SELECT DISTINCT category, subcategory , product_name FROM gold.dim_products
ORDER BY 1,2,3;

-- DATE Exlporation 


-- Find the date of the first and last order
-- How many years of sales are avaliable
 SELECT 
 MIN(order_date) AS First_order_date,
 MAX(order_date) AS Last_order_date,
 DATEDIFF(year,MIN(order_date),MAX(order_date)) AS order_range_years
 FROM Gold.fact_sales;

  -- Find the youngest and oldest customer
 SELECT
	MIN(birthdate) AS oldest_customer_age,
	MAX(birthdate) AS youngest_customer_age,
	DATEDIFF(year,MIN(birthdate),GETDATE ()) AS oldest_age,
	DATEDIFF(year,MAX(birthdate),GETDATE ()) AS youngest_age
FROM gold.dim_customers;

-- MEASURE EXPLORATION 

-- Find the total Sales
SELECT SUM(sales_amount) AS Total_sales FROM gold.fact_sales
-- Find how many items are sold 
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales
-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales
-- Find the Total number of Orders
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales
-- Find the total number of products 
SELECT COUNT(DISTINCT product_name) AS total_products FROM gold.dim_products
-- Find the total number of customers that has placed an order
SELECT COUNT(Distinct customer_key) AS total_customers FROM gold.fact_sales

USE DataWarehouseAnalytics

-- Generate Report that shows all key metrics of the business 
 SELECT 'Total Sales ' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
 UNION ALL
 SELECT 'Total Quantity', SUM(quantity) AS total_quantity FROM gold.fact_sales
 UNION ALL
 SELECT 'Average Price',AVG(price) AS avg_price FROM gold.fact_sales
 UNION ALL
 SELECT 'Total Nr. Orders',COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales
 UNION ALL
 SELECT 'Total Nr. Products',COUNT(DISTINCT product_name) AS total_products FROM gold.dim_products
 UNION ALL
 SELECT 'Total Nr. Customers',COUNT(Distinct customer_key) AS total_customers FROM gold.fact_sales


-- 5. Magnitude 
-- Find total customers by countires
	SELECT 
	country,
	COUNT(customer_key) AS Total_customers
	FROM gold.dim_customers
	GROUP BY country
	ORDER BY Total_customers DESC;
-- Find the total customers by gender
	SELECT 
	gender,
	COUNT(customer_key) AS Total_customers
	FROM gold.dim_customers
	GROUP BY gender
	ORDER BY Total_customers DESC;
-- Find total products by category
SELECT 
category,
COUNT(product_key) AS Total_products
FROM gold.dim_products
GROUP BY category
ORDER BY Total_products DESC
-- What is the average costs in each category
SELECT 
category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- What is the total revenue generated for each category
SELECT 
p.category,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP  BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each gender
SELECT
c.gender,
SUM(f.sales_amount) AS total_revneue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.gender
Order By total_revneue DESC;

-- Find total revenue is generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revneue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
Order By total_revneue DESC;

-- What is the distribution of sold items across countries

	SELECT 
		c.country,
		SUM(f.quantity) AS total_sold_items
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_customers c
	ON c.customer_key = f.customer_key
	GROUP BY 
	c.country
	Order By total_sold_items  DESC;

-- 6. Ranking Top N - Bottom N

-- Which 5 products generate the Highest revenue
		SELECT
			*
		FROM 
		(SELECT
			p.product_name,
			SUM(f.sales_amount) AS Total_revenue,
			ROW_NUMBER () OVER (ORDER BY SUM(f.sales_amount) DESC) AS Rank_Products
		FROM gold.fact_sales f
		LEFT JOIN gold.dim_products p
		ON p.product_key = f.product_key
		GROUP BY p.product_name)t
		WHERE Rank_Products <= 5

-- What is the total revenue generated for each subcategory
	SELECT TOP 5
		p.subcategory,
		SUM(f.sales_amount) as total_revenue
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP  BY p.subcategory
	ORDER BY total_revenue DESC;

	 

-- What are the worst performing products in terms of sales
	SELECT TOP 5
		p.product_name,
		SUM(f.sales_amount) as total_revenue
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP  BY p.product_name
	ORDER BY total_revenue ;

-- Find the top 10 customers who have generated the highest revenue
	SELECT  TOP 10
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revneue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
		c.customer_key,
		c.first_name,
		c.last_name
Order By total_revneue DESC

-- The 3 customers with the fewest orders placed
SELECT  TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
		c.customer_key,
		c.first_name,
		c.last_name
ORDER BY total_orders ASC






